Revert "fix: Revert  rename module to resources and look for all reso…
kyma-project/opentelemetry-collector-components pull request #124
Opened 2024-09-10 10:04 UTC by rakesh-garimella

…urces (#123)"

This reverts commit 2d056bd1f9bbcae18aa9713a80fa4dee2e318778.

## Description

Changes proposed in this pull request (what was done and why):

- 

Changes refer to particular issues, PRs or documents:

- 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] If the change is user-facing, the documentation has been adjusted.
- [ ] The feature is unit-tested.
- [ ] The feature is e2e-tested.

2024-09-10 15:53 UTC, NHingerl submitted a review, later dismissed

2024-09-11 09:07 UTC, hisarbalik requested changes

2024-09-11 09:07 UTC, hisarbalik commented on receiver/kymastatsreceiver/README.md
> +      kyma.resource.name:
```suggestion
      k8s.resource.name:
```

2024-09-11 09:09 UTC, hisarbalik approved these changes

2024-09-11 09:30 UTC, NHingerl commented on receiver/kymastatsreceiver/documentation.md
> +The resource status state, metric value is 1 for last scraped resource status state, including state as metric attribute.
```suggestion
The resource status state, metric value is 1 for the last scraped resource status state, including state as metric attribute.
```

2024-09-11 10:33 UTC, NHingerl approved these changes

2024-09-11 11:10 UTC, NHingerl approved these changes

2024-09-11 11:12 UTC, hisarbalik approved these changes

2024-09-11 11:13 UTC, merged